# Generated by Django 4.0.6 on 2022-08-27 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SignUp', '0002_alter_signup_birth_date_alter_signup_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='signup',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
